# runs the pipeline to ensure any new serials uploaded to airtable are searched

name: run-pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
  
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
    steps:
      # workflow setup
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.2
      # run makefile targets
      - name: run setup
        run: make setup
      - name: run full pipeline
        run: make -B
      # exit if there are no changes
      - name: check for changes
        run: git diff --exit-code
      # commit and push changes
      - name: commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update search results"
