name: upload-raw

on:
  push:
    branches: ["main"]
    paths: ["raw/**"]
  workflow_dispatch:
    inputs:
    
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GOOGLE_DRIVE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS_JSON }}
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.2
      - name: run setup
        run: make setup
      - name: save drive credentials to json
        run: echo $GOOGLE_DRIVE_CREDENTIALS_JSON > credentials.json
      - name: run script
        run: poetry run python scripts/upload_raw.py
